version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(asctime)s {%(pathname)s:%(lineno)d} %(levelname)s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: logs/classify.log
    maxBytes: 104857600
    backupCount: 10
root:
  level: INFO
  handlers: [console,file]
elasticsearch:
  level: INFO
  handlers: [console,file]

